name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job via CURL
        run: |
          curl -X POST "http://<JENKINS_HOST>:8080/job/<JOB_NAME>/build" \
          --user "<USERNAME>:<API_TOKEN>"
